Add sample code for 24 segments bargraph
thingsSDK/ht16k33 pull request #2
Opened 2017-05-16 19:02 UTC by chevdor

2018-01-11 19:08 UTC, chevdor commented
Hi there, is anything blocking the merging of this PR?

2018-06-19 21:07 UTC, chevdor commented
Hi @chalkers do you need any change in this PR or could it be merged?

2018-08-12 06:36 UTC, chalkers requested changes
Hi @chevdor 

Attached are some comments regarding this pull request.

It needs a little work. 

Thanks
Andrew

2018-08-12 06:36 UTC, chalkers commented on README.md
> +//Squint a little and you can see the faces!
This comment isn't really for this bargraph

2018-08-12 06:36 UTC, chalkers commented on README.md
> +## Example Code for 24 Segment Bargrah
sp. Bargraph

2018-08-12 06:36 UTC, chalkers commented on README.md
> +import { connect8x8BicolorMatrix } from '@thingssdk/ht16k33/espruino';
connect8x8BicolorMatrix is for Bi Color Displays

A more appropriate API would be BicolorBargraph

2018-08-12 06:36 UTC, chalkers commented on README.md
> +    const matrix = connect8x8BicolorMatrix()
mayby `const bargraph` and again 8x8BicolorMatrix isn't descriptive API...

2018-08-12 06:36 UTC, chalkers commented on README.md
> +    //Draws Neutral Face after 1 second
Comment not descriptive of what this is doing.

2018-08-12 06:36 UTC, chalkers commented on README.md
> +    console.log('interval = ' + intervalId)
Why?

2018-09-10 13:54 UTC, chevdor commented
Hi @chalkers 
I have pushed a fix that should address what you mentioned in your feedback.

2021-07-08 08:44 UTC, chevdor commented
This PR has been ready for a while on my end. Can it be reviewed and either merged or closed please ?

2021-07-14 07:19 UTC, chevdor commented
Dormant review...

2021-07-14 07:19 UTC, closed without merging